version: '3.7'
services:
  mysql:
    container_name: mysql
    image: registry.cn-hangzhou.aliyuncs.com/qidian_registry/mysql:5.17
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /usr/local/src/my.cnf:/etc/my.cnf
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /usr/local/freeswitch/recordings/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Zswitch69686996
    networks:
      - code-network
  web:
    container_name: zsitsms
    image: registry.cn-hangzhou.aliyuncs.com/qidian_registry/php:5.2
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /var/www/html/:/var/www/html/
      - /usr/local/freeswitch/recordings/:/var/www/html/zsitsms/downloads/recordings/
    links:
      - mysql
    networks:
      - code-network
  icproxy:
    container_name: icproxy
    image: registry.cn-hangzhou.aliyuncs.com/qidian_registry/icproxy:latest
    restart: always
    ports:
      - 8003:8003
    networks:
      - code-network
networks:
  code-network:
    driver: bridge
