version: '3'
services:
   zabbix-agent:
    image: "zabbix/zabbix-agent:centos-4.4-latest"
    container_name: "zabbix-agent"
    restart: "always"
    environment:
      - "ZBX_HOSTNAME=zabbix-agent"
      - "ZBX_SERVER_HOST=172.17.0.1"
      - "ZBX_SERVER_PORT=10051"
      - "TZ=Asia/Shanghai"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    network_mode: bridge
    ports:
      - "10050:10050"
